language: node_js
node_js:
  - 0.11
  - 0.10
beforeScript:
  - npm install
  - npm install -g karma-phantomjs-launcher
script:
  - node_modules/.bin/karma start --single--run --browsers PhantomJS

notifications:
    on_success: never
    on_failure: always
    slack: dsd-meetme:pZvZrzGoESPNVXScLAnMf10X